### ISSUE TITLE
Mismatch: subOrders' api mismatch to document.

### ISSUE THREAD

**Issue by YanB25** [wwyf/Waterfall-backend#13]
According to the document, `/api/order/subOrder (get)` and `/api/order/mainOrder/{mainOrderId}/subOrders (get)`
response something like
```
{
        "mainOrderId": "string",
}
```
However I get `mainorder`(all small letter) instead of`mainOrderId`.

## Suggestion
To fix this, change the **document** rather than the backend.

@wwyf 
@gtbl2012

**Comment by wwyf** [comment]
got it!

**Comment by wwyf** [comment]
For the consistency of the database field and JSON field, I will change the document in https://github.com/wwyf/Waterfall.

**Comment by wwyf** [comment]
fix in https://github.com/wwyf/Waterfall/pull/37#issuecomment-496378742.
I'll close this issue.
