### ISSUE TITLE
NOTICE: Possiple errors in api implementation

### ISSUE THREAD

**Issue by iffiX** [wwyf/Waterfall-backend#15]
mainorder_api.py: L47: res_query_results == None?
mainorder_api.py: L156: res_query_results == None?
mainorder_api.py: L195: res_query_results == None?
mainorder_api.py: L228: res_query_results == None?

suborder_api.py: L27: res_query_results == None?
suborder_api.py: L123: res_query_results == None?
suborder_api.py: L158: res_query_results == None?
suborder_api.py: L191: res_query_results == None?

user_api: L34: None?
user_api: L174: None?
另外edit_user_info L175 应该是or逻辑
add_user是否应该只允许manager角色的用户调用？如果usertype不是manager是否应该禁止？

**Comment by wwyf** [comment]
I have fixed these problems that you reported.
```
res_query_results == None?
```
Now it remains four failed test cases.
look #19

**Comment by wwyf** [comment]
Thanks notice. I'll close this issue.
