### ISSUE TITLE
Change Request: place main order should not provide those fields

### ISSUE THREAD

**Issue by YanB25** [wwyf/Waterfall-backend#17]
in api `/api/order/mainOrder (post)`
```
{
  "name": "鲜天下实例订单名称",
  "summary": "鲜天下示例订单概述，我司需要大批量的i7-9900K。",
  "deadline": "2019-02-05",
  "address": "广州市广州大学城外环东路132号",
  "quantity": 50,
  "price": 100,
  "createuser": 1,
  "comments": "空备注",
  "phone": 13538383838
}
```
Frontend do NOT need to provide
1. `createuser`, because backend gets `user id` by cookies
1. `phone`, because `phone` has already been stored in `user profile`. Backend is able to fetch this field by accessing the database. No need require frontends to provide.

**Comment by wwyf** [comment]
`phone` should be included in the request so that you can place an order by other contacts in the same company.

**Comment by wwyf** [comment]
I'll fix the `createuser` field soon.

**Comment by YanB25** [comment]
`phone` should be an **optional** field. If not specified, should be the phone number in the user profile by default.

**Comment by wwyf** [comment]
I think this can be done in frontend.
You can fill the input box with the phone number in user profile by default.

**Comment by wwyf** [comment]
@gtbl2012 
What do you think about this?

**Comment by YanB25** [comment]
A comparison:
## implement in frontend
### fetch once
To get the `phone` number, the frontend can fetch `/api/user/{userid}`(**once**) to get the user profile, and store the `phone` field in the global storage(so that every component in the frontend can access to the `phone` number).

Frontend can fetch `/api/user/{userid}` when the user firstly open our pages, but ...
- what if the frontend want to postpone fetching `/api/user/{userid}` until it's really necessary?
- It's currently difficult to store  **global** and **structural** data in frontend(since we didn't use `vuex`, an official component to do the storage, but yes, we can use it if really necessary.)
### fetch when needed
Frontend can fetch `/api/user/{userid}` every time when `phone` field is needed. This causes unnecessary network overhead.

## implement in backend
The backend only needs to check whether `phone` exists and ask database for the field.
It's annoying to write `db` codes, but it's more natural in logic. Data flows only in our server.

**Comment by wwyf** [comment]
I will fix the `phone` field.
