### ISSUE TITLE
CRITICAL BUG: deleted orders are not reverted.

### ISSUE THREAD

**Issue by YanB25** [wwyf/Waterfall-backend#30]
If I delete a subOrder, then `remain_quentity` of the mainOrder will not **revert**. 
This bug should be fix quickly.

ALSO, when a mainOrder is canceled, **all the related subOrders should be canceled too**.

**Comment by wwyf** [comment]
Now I'll fix  “ when a mainOrder is canceled, all the related subOrders should be canceled too.”
