### ISSUE TITLE
Discussion: What does delete user means?

### ISSUE THREAD

**Issue by YanB25** [wwyf/Waterfall-backend#32]
Does delete user really necessary? What does it mean?

How to handle all the relative orders created by that user?

Maybe will never **delete** a user, we just make it's status `1`.

**Comment by YanB25** [comment]
@gtbl2012 @wwyf

**Comment by YanB25** [comment]
If so, frontend should change. Delete the `delete-icon` in the "user management panel"

**Comment by wwyf** [comment]
Good question!

**Comment by wwyf** [comment]
Agree with you !
