### ISSUE TITLE
API requested: username check and fetch suborders

### ISSUE THREAD

**Issue by YanB25** [wwyf/Waterfall-backend#6]
- /apis/user/check/{username}
check whether `username` is available to use.
`username` satisfies `[a-zA-Z0-9]+`
- /apis/order/mainOrder/{mainOrderId}/subOrders
get all the suborders `id` connected to the main orders.

**Comment by wwyf** [comment]
fixed it.
I'll close this issue.

**Comment by YanB25** [comment]
After further consideration, I think `/apis/order/mainOrder/{mainOrderId}/subOrders` should response the `subOrder` data, rather than the `id` only.
@gtbl2012
