### ISSUE TITLE
NOTICE: Implementation notice in /apis/user/{userid}

### ISSUE THREAD

**Issue by YanB25** [wwyf/Waterfall-backend#7]
the body of `/apis/user/{userid}` would be 
```
{
  "username": "wyf",
  "password": "123456",
  "email": "klfsl@163.com",
  "phone": "13538383838",
  "balance": 999,
  "role": "provider",
  "status": 0
}
```
Body of HTTP requests from frontend **may** include `username`, `role` or `status` fields, but backend **should** ignore theses fields.

**Comment by wwyf** [comment]
I know what you mean.
In the implementation, the `username` field will always be ignored.
And only for `manager`, he/she can modify the `role` field and the `status` field, user which  is not `manager` will not modify these field though you pass these to backend.

**Comment by YanB25** [comment]
Perfect.
